# Generated by Django 2.2.1 on 2019-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Banks_Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='question_banks/')),
            ],
        ),
        migrations.CreateModel(
            name='Questions_Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('qb_name', models.TextField(max_length=30)),
                ('statement', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=100)),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
    ]
