# Generated by Django 2.2.1 on 2019-11-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_Main',
            fields=[
                ('qb_name', models.TextField(max_length=30)),
                ('statement', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=3)),
                ('tag', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
