# Generated by Django 2.2.6 on 2019-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='created_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('num_ques', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('ques_id', models.CharField(max_length=150)),
            ],
        ),
    ]
