# Generated by Django 2.2.1 on 2019-11-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_questions_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_main',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
