# Generated by Django 2.2.1 on 2019-11-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_created_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_banks_main',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questions_main',
            name='qb_name',
            field=models.TextField(max_length=50),
        ),
    ]
