# Generated by Django 2.2.1 on 2019-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20191123_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('qb_name', models.CharField(max_length=50)),
                ('statement', models.TextField()),
                ('marks', models.IntegerField()),
                ('subquestions', models.IntegerField()),
                ('ques_id_string', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_module_id', models.IntegerField()),
                ('statement', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('marks', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=100)),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='questions_main',
            name='qb_name',
            field=models.CharField(max_length=50),
        ),
    ]
