# Generated by Django 2.2.1 on 2019-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_questions_main_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_main',
            name='marks',
            field=models.TextField(),
        ),
    ]
