# Generated by Django 2.2.1 on 2019-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20191124_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='created_paper',
            name='num_ques_modules',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='created_paper',
            name='ques_module_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
