# Generated by Django 2.2.1 on 2019-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20191122_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_main',
            name='marks',
            field=models.IntegerField(default=100),
        ),
    ]
