# Generated by Django 2.2.1 on 2019-11-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20191124_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='created_paper',
            name='total_sum_ques',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
