# Generated by Django 2.2.1 on 2019-11-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20191122_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_main',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=100),
        ),
    ]
