# Generated by Django 2.2.1 on 2019-11-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_created_paper_total_sum_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='created_paper',
            name='duration',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
